defmodule KinoAtpClient.SystemOnTptp do
  @moduledoc """
  A Smart Cell dedicated to executing TH0/TPTP problems via SystemOnTPTP.

  In addition to running a chosen prover, the cell drives live syntax and
  type feedback in the editor: every debounced keystroke fires a
  `"check_syntax"` event, the cell calls `AtpClient.Lint.analyze/2`, and
  the resulting diagnostics and declared symbols are streamed back to
  the Monaco editor for marker placement, hover cards, and completion.
  """

  use Kino.JS, assets_path: "lib/assets/system_on_tptp"
  use Kino.JS.Live
  use Kino.SmartCell, name: "SystemOnTPTP"

  alias AtpClient.SystemOnTptp
  alias AtpClient.Lint
  alias AtpClient.Lint.Report

  @impl true
  def init(attrs, ctx) do
    state = %{
      problem_str:
        Map.get(
          attrs,
          "problem_str",
          "thf(test, conjecture, $true => $true)."
        ),
      system: Map.get(attrs, "system", "Leo-III---1.7.20"),
      time_limit: Map.get(attrs, "time_limit", 5),
      theme: Map.get(attrs, "theme", "Dracula"),
      tptp4x_enabled: Map.get(attrs, "tptp4x_enabled", true),
      solvers: ["Leo-III---1.7.20"],
      lint_task: nil
    }

    send(self(), :fetch_solvers)
    {:ok, assign(ctx, state)}
  end

  @impl true
  def handle_connect(ctx) do
    payload = Map.drop(ctx.assigns, [:lint_task])
    {:ok, payload, ctx}
  end

  @impl true
  def handle_info(:fetch_solvers, ctx) do
    AtpClient.SystemOnTptp.Provers.refresh_systems_list()
    found_solvers = AtpClient.SystemOnTptp.list_provers()
    broadcast_event(ctx, "solvers_fetched", %{"solvers" => found_solvers})
    {:noreply, assign(ctx, solvers: found_solvers)}
  end

  @impl true
  def handle_info({:preview_result, {:ok, result}}, ctx) do
    broadcast_event(ctx, "preview", %{"text" => result})
    {:noreply, ctx}
  end

  @impl true
  def handle_info({:preview_result, {:error, reason}}, ctx) do
    broadcast_event(ctx, "preview_error", %{"message" => to_string(reason)})
    {:noreply, ctx}
  end

  @impl true
  def handle_info(
        {ref, {:lint_ok, %Report{} = report}},
        %{assigns: %{lint_task: %Task{ref: ref}}} = ctx
      ) do
    Process.demonitor(ref, [:flush])

    broadcast_event(ctx, "lint_result", %{
      "diagnostics" => Enum.map(report.diagnostics, &Map.from_struct/1),
      "symbols" => Enum.map(report.symbols, &Map.from_struct/1)
    })

    {:noreply, assign(ctx, lint_task: nil)}
  end

  @impl true
  def handle_info({ref, {:lint_ok, %Report{}}}, ctx) when is_reference(ref) do
    Process.demonitor(ref, [:flush])
    {:noreply, ctx}
  end

  @impl true
  def handle_info({:DOWN, _ref, :process, _pid, _reason}, ctx) do
    {:noreply, ctx}
  end

  @impl true
  def handle_event("update", params, ctx) do
    allowed = ~w(problem_str system time_limit theme tptp4x_enabled)

    atom_params =
      for {k, v} <- params, k in allowed, into: %{} do
        {String.to_existing_atom(k), v}
      end

    {:noreply, assign(ctx, Map.merge(ctx.assigns, atom_params))}
  end

  @impl true
  def handle_event("quick_eval_btn", %{"action" => "solve"}, ctx) do
    parent = self()
    %{problem_str: prob, system: sys, time_limit: tl} = ctx.assigns

    Task.start(fn ->
      res =
        case SystemOnTptp.query_system(prob, sys, time_limit_sec: tl, raw: true) do
          {:ok, result} -> {:ok, result}
          {:error, msg} -> {:error, "API Error: #{inspect(msg)}"}
        end

      send(parent, {:preview_result, res})
    end)

    {:noreply, ctx}
  end

  @impl true
  def handle_event("check_syntax", %{"problem" => problem}, ctx) when is_binary(problem) do
    ctx = cancel_lint_task(ctx)
    enabled_tptp4x = Map.get(ctx.assigns, :tptp4x_enabled, true)

    backends = if enabled_tptp4x, do: [:local, :tptp4x], else: [:local]

    task =
      Task.async(fn ->
        try do
          {:lint_ok, Lint.analyze(problem, backends: backends)}
        rescue
          _ -> {:lint_ok, %Report{diagnostics: [], symbols: []}}
        end
      end)

    {:noreply, assign(ctx, lint_task: task)}
  end

  defp cancel_lint_task(%{assigns: %{lint_task: %Task{} = task}} = ctx) do
    Task.shutdown(task, :brutal_kill)
    assign(ctx, lint_task: nil)
  end

  defp cancel_lint_task(ctx), do: ctx

  @impl true
  def to_attrs(ctx) do
    Map.take(ctx.assigns, [:problem_str, :system, :time_limit, :theme, :tptp4x_enabled])
  end

  @impl true
  def to_source(%{problem_str: prob, system: sys, time_limit: tl}) do
    """
    # Generated by SystemOnTPTP Smart Cell
    problem = #{inspect(prob)}
    system_name = #{inspect(sys)}
    time_limit = #{inspect(tl)}

    case AtpClient.SystemOnTptp.query_system(problem, system_name, time_limit_sec: time_limit, raw: true) do
      {:ok, result} ->
        IO.puts(result)
        result

      {:error, reason} ->
        raise "Error: \#{inspect(reason)}"
    end
    """
  end
end
